# Site settings
title: College Blog
email: keitca01@luther.edu
description: A blog about my college experience.
baseurl: "/college-blog"
twitter_username: breezyranchgoth
avatar: "https://pbs.twimg.com/profile_images/724434280412139521/AYHv30qj_bigger.jpg" # Set footer avatar
paginate: 3

# Build settings
markdown: kramdown
permalink: /:title

# Default Settings
defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      author: "Cara Keith" # Set default author name
      categories: "experiences"
      layout: "post"
      comments: true
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: "page"
